name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: corepack enable

      - uses: cypress-io/github-action@v6
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000/en'
          install-command: yarn --immutable

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cypress E2E Videos
          path: cypress/videos
